sudo: required
services:
  - docker

before_install:
  - docker build -t kingsleywang/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true kingsleywang/react-test npm test -- --coverage

after_success:
  - docker build -t kingsleywang/multi-client ./client
  - docker build -t kingsleywang/multi-server ./server
  - docker build -t kingsleywang/multi-nginx ./nginx
  - docker build -t kingsleywang/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kingsleywang/multi-client
  - docker push kingsleywang/multi-server
  - docker push kingsleywang/multi-nginx
  - docker push kingsleywang/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-132343472762
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
